== Al Lector

Ya seas amigo o enemigo de la Verdad,
las cosas declaradas en este libro pueden serte útiles si las lees humilde y sobriamente;
porque son engendradas de esa Vida inocente contra la que la serpiente siempre guerrea.
Por tanto, cuando comiences y te dispongas a leerlas,
hazlo en el temor y espanto del Señor Dios,
postrándote en humildad y buscando sentir al Testigo de Dios en tu propia conciencia,
para que puedas leer y verdaderamente entender.
Y a medida que te mantengas en la manifestación del Espíritu en ti mismo, y leas en ella,
sentirás cuando las cosas declaradas alcanzan y le hablan
a tu condición. Entonces mantente en silencio y quieto,
y no permitas que el enojo o la envidia se levanten en tu corazón,
a lo que la serpiente a veces te provocará;
porque si cedes ante esto y le permites que se levante, te impedirá aprovecharlas.
Por tanto, lee en humildad y recibe esto en el mismo amor con que es declarado.
Entonces sentirás el peso de la verdad, y cosecharás favor y provecho de ella;
y sentirás, cuánto has llegado a ser testigo de la redención por el poder de Cristo,
o dónde te detiene aún la serpiente, y a qué estás todavía en esclavitud.
Y cuando veas tus cadenas en Su Luz, vuélvete a la Luz y rechaza todo lo demás, para que,
sin importar qué sean esas cadenas, sean juzgadas,
crucificadas en la cruz y consumidas en el fuego.
_Debes entrar por esta puerta, la espada encendida,_
o serás excluido del paraíso de Dios y mantenido apartado del Árbol de la vida.
Pero a medida que te sometas al Señor y llegues a conocer Su obra,
Él juzgará tus concupiscencias, crucificará tu vida y destruirá el cuerpo del pecado;
y así, a través de la muerte,
Él engendrará una nueva vida en la que experimentarás
un cambio perfecto de lo terrenal a lo celestial.
Aquí gozarás del Señor y de Su presencia, poder y bondad,
y al fin te sentarás calmadamente en gozo, paz y bendición.

[.signed-section-signature]
William Smith

[.signed-section-context-close]
Primer mes, 1661
