== Capítulo I. El Estado del Hombre en la Creación

El Señor Dios de vida y poder, que es por los siglos de los siglos,
conforme al beneplácito de Su voluntad, y según el designio de Su propio corazón,
dio a luz una creación pura en Su sabiduría. Mediante Su eterna Palabra vivificante,
dividió y separó la materia,
que en el caos se encontraba amontonada en confusión.
Todo lo que ordenó por medio de Su Palabra se cumplió;
y tal como dijo que debía ser, así fue hecho.
En Su sabiduría, una creación pura fue completada.

Cuando extendió los cielos y puso las lumbreras en ellos;
cuando fundó la tierra y produjo la hierba verde y los árboles en ella;
cuando separó las aguas y se multiplicaron los peces en ellas;
cuando las aves del cielo volaron en el aire,
y los cuadrúpedos y reptiles caminaron por la tierra; entonces,
la eterna Palabra (en sabiduría) creó al hombre a Su propia imagen,
y sopló en él aliento de Vida, de manera que se convirtió en un alma viviente.
El Señor Dios lo llenó de sabiduría y entendimiento,
y le dio dominio sobre todas las obras de Sus manos,
de modo que gobernó sobre todo en la sabiduría de Dios.
El hombre estaba entonces en la sabiduría de Dios,
y recibía consejo y caminaba en la Vida santa.
Caminaba en el paraíso del placer, se alimentaba del Árbol de la Vida,
y vivía en una quieta y tranquila comunión con su Dios,
donde su alma viviente moraba en la virtud vivificante de Dios,
recibiendo siempre el aliento de Su Vida.
Así vivía el hombre, en una unidad pura con el Dios que lo había hecho,
y la semejanza de la Vida santa estaba sobre él. Él moraba en el poder,
sabiduría y fuerza de Dios, y llevaba Su imagen en justicia y verdadera santidad,
sin mezcla alguna.
Todas las cosas permanecían claras y limpias en la
debida separación en la que fueron creadas,
y no había ninguna mezcla que las contaminara.

Entonces la Sabiduría contempló Su obra, y he aquí,
que era buena en gran manera ante Sus ojos.
Él se complacía y deleitaba grandemente en ella, y Su misericordia, amor,
bondad y ternura eran para ella, y Su bendición y paz estaban sobre ella.
El hombre gozaba de la presencia viva de Su Hacedor, y así participaba de Su amor,
misericordia, bendición y paz.
Tenía libre acceso al manantial de Vida, y no había nada que se interpusiera en su camino.
Así era exhalado continuamente el aliento de Vida, y en él vivía el alma,
estando en perfecta unidad con él. Esto no era algo del exterior, sino más bien,
la operación pura del poder y sabiduría de Dios en el interior.
Sí, Dios formó un cuerpo terrenal y dio a luz una creación visible,
para llenarla de Su tesoro celestial--de Su propia Vida Santa, la cual Él sopló en ella.
Así, engendró el Creador al hombre según Su propia imagen,
y no había mezcla en su vida y ser.
El cuerpo terrenal fue hecho una vasija compuesta,
preparada y formada en la sabiduría de Dios para
contener la imagen incorruptible de la Vida.
En el principio,
la Vida de Dios fluía libremente en el hombre y lo llenaba de Su ser celestial,
y no había mezcla de lo terrenal en su vida y ser.

Así era el hombre que fue creado según Dios en justicia y verdadera santidad,
y que llevaba Su imagen en perfecta gloria.
El cuerpo fue preparado como una vasija apta para el uso de Aquel que lo creó,
y para llenarlo de Su vida pura y santa.
Aquí, el hombre estaba en obediencia al Padre de los espíritus;
Aquel que lo había hecho un hombre espiritual, santo y justo,
y lo había alimentado con comida espiritual y santa.
De este modo, el hombre al principio no poseía voluntad o deseo tras ninguna cosa creada,
sino que se mantenía en la voluntad eterna y señoreaba todas las criaturas.
Su único deseo era gozar de la Vida santa en la que había sido creado y engendrado.
Y de todo lo que deseaba participar en la Vida,
le era proporcionado según el beneplácito del Creador;
pues él vivía en el gozo puro del eterno Ser,
en Quien era diariamente consolado y continuamente saciado.
En este estado no había pecado o maldad cometido por él. Ninguna maldición podía alcanzarlo;
ninguna muerte estaba sobre él; ninguna tumba lo detenía;
ninguna ira podía salir contra él. En misericordia vivía,
y la misericordia era su porción. El deleite del hombre era su Creador,
y caminaba con Él día y noche, gozando de verdadera libertad en el paraíso,
y de libre acceso al Árbol de la Vida.

Así, pues, el hombre fue creado en justicia, sirvió a Dios en justicia,
y vivió en la Vida de justicia, sin conocer la mezcla de ninguna cosa injusta.
Fue creado en la sabiduría de Dios y llevó la imagen de Dios,
extrayendo el aliento de Vida de la Fuente santa.
Se mantuvo en la esencia eterna de la naturaleza divina, produciendo las obras de Dios;
y Dios descansó de todas las obras que había hecho.
