== Capítulo II. El Estado del Hombre en la Degeneración

Cuando la creación pura fue terminada en el poder y sabiduría eternos,
descansó en el santo orden de la Vida,
y estaba en armonía pura y en unidad con el Creador;
y así debió haber permanecido--en el santo orden--y nunca debió haber sido movida,
a no ser por el poder y la sabiduría de la Vida.
Sin embargo, una parte de la creación no había guardado su dignidad o estado,^
footnote:[Judas 1:6 LBLA]
sino que se había salido de la sabiduría, quebrantado el orden santo,
y anhelado igualdad con la Esencia santa.
Por esta razón fue arrojada por el poder, llevada a las partes más bajas de la creación,
y allí, se le asignó su lugar y morada, a la mayor distancia de Dios.
En efecto, la ira de Dios se encendió contra ella, y en Su ira,
la arrojó. Su ira permanece sobre ella,
y ha sido sellada en el enojo e ira sin posibilidad de recuperación. Este es el lugar
designado para la parte de la creación que no se mantuvo en el santo orden,
sino que anheló ser igual al poder creador.^
footnote:[Isaías 14:13-15]
Su nombre es la serpiente, el diablo, y su morada es el infierno, el pozo sin fondo,
donde el Todopoderoso Dios manifiesta ira sin cesar.

Cuando esta ambiciosa parte de la creación fue lanzada a las partes más profundas,
se volvió bestial, terrenal, sensual y diabólica,
y era más astuta que cualquier otro animal del campo.
Habiendo perdido su lugar en la creación pura,
y habiendo sido arrojada a la separación de Dios
(donde la ira o enemistad se experimenta sin cesar),
entonces trabajó con su astucia para sacar del orden
lo que aún conservaba su puesto y orden;
es decir,
_procuró engendrar un movimiento en el hombre que
estuviera fuera del movimiento del poder de Dios._

El Señor Dios le había dado un mandato al hombre,
el día que lo puso en el paraíso. Le dijo:
"`Mas del árbol de la ciencia del bien y del mal no comerás;
porque el día que de él comieres, ciertamente morirás.`"^
footnote:[Génesis 2:17]
Sabiendo esto, la serpiente tentó a la mujer, porque era la más cercana al hombre,
habiéndosele dado como compañera.
Sutilmente la tentó a comer del fruto del árbol que Dios había prohibido, cuando le dijo:
"`¿Conque Dios os ha dicho: No comáis de todo árbol del huerto?
Y la mujer respondió a la serpiente: Del fruto de los árboles del huerto podemos comer;
pero del fruto del árbol que está en medio del huerto dijo Dios: No comeréis de él,
ni le tocaréis, para que no muráis. Entonces la serpiente dijo a la mujer: No moriréis;
sino que sabe Dios que el día que comáis de él, serán abiertos vuestros ojos,
y seréis como Dios, sabiendo el bien y el mal.`"^
footnote:[Génesis 3:1-5]

Y cuando la serpiente halló cabida en la mujer con esta tentación,
y atrajo su mente para que la mirara,
entonces ella vio que el árbol era bueno para comer, agradable a los ojos,
y codiciable para alcanzar la sabiduría. Ella lo tomó y comió,
y también le dio a su esposo, y él comió. Y así,
por medio de la parte más débil de la creación, logró alcanzar a la más fuerte,
y de este modo entró y prevaleció. Entonces, ¡ay!,
_la creación se salió del poder y se estableció en contra del poder;_ y por ende,
el poder de Dios (en el que debió haber permanecido y descansado) fue transgredido.
Así se salió la creación del orden puro,
y el hombre cayó del poder y de la sabiduría del Creador,
al escuchar la voz del engañador y transgredir contra el Dios de su Vida.

De esta manera, el hombre se volvió un "`sarmiento degenerado de una vid extraña,`"^
footnote:[Jeremías 2:21 LBLA]
y perdió su autoridad en la creación. Habiéndose sometido a la astucia de la serpiente,
fue echado del paraíso y arrojado a la tierra,
donde se corrompió y contaminó con la mezcla de las propiedades terrenales caídas.
En un instante todas las facultades y propiedades del hombre cambiaron,
y en seguida pasó de una imagen celestial a una imagen terrenal.
De esta forma se convirtió en un hombre terrenal, con una mente terrenal y carnal,
la cual era enemistad contra Dios,
y con una sabiduría terrenal que es sensual y diabólica,
en la que la serpiente era exaltada y tenía dominio sobre el hombre.
Y así la creación pura, que en el principio estaba en la misericordia y amor del Creador,
se perdió y fue esclavizada, habiendo caído en mezclas oscuras;
y allí comenzó a gemir y a afligirse con dolores de parto.
En esta mezcla la serpiente obró engañosamente,
de modo que el hombre se convirtió en objeto de ira y maldición,
ensombrecido por la muerte y rodeado por el infierno, encadenado al tormento,
la angustia, el dolor y el temor.

Así perdió el hombre la imagen celestial en la cual fue creado,
y se formó en él la imagen terrenal de la serpiente.
El mundo entró en su corazón, y la serpiente se sentó en el mundo y ejerció su poder,
y se convirtió en el dios de este mundo.
Y luego, el Árbol de la Vida fue custodiado con querubines y con una espada encendida,
y adondequiera que se volvía el hombre (por la astucia de
la serpiente) para buscar y gustar del Árbol de la Vida,
la espada encendida se revolvía por todos lados y le salía al encuentro.

Pero luego la compasión de la Eterna Misericordia se conmovió, y Su amor se extendió,
y se designó una Semilla que heriría la cabeza de la serpiente,
y recobraría al hombre nuevamente de la mezcla de la oscuridad donde la ira es conocida,
y lo restauraría al amor y a la misericordia que
eran anteriormente su porción. Sin embargo,
la mente que había caído a la tierra,
no pudo ver ninguna belleza o hermosura en esta Semilla como para desear o amar Su aparición,
sino que ha permanecido en enemistad contra ella.
Pues una imagen terrenal resulta más deseable para una mente terrenal,
y le parece lo más hermoso.

Así cayó el hombre y se degeneró,
y la tierra se ha convertido en su morada y habitación.
Aquí posee una imagen engendrada por la serpiente,
y se alimenta de la vieja creación.
