== Capítulo III. El Estado del Hombre en la Separación

Cuando el hombre transgredió y pecó contra el poder y la sabiduría de Dios,
y fue echado del paraíso, y excluido del Árbol de la Vida,
se convirtió en siervo de un sutil engaño, y siguió sus direcciones hacia abajo,
volviéndose un errante en la tierra,
en la que la serpiente lo guiaba por partes tenebrosas y caminos secos.
Y así, al unirse a la serpiente, se convirtió en enemigo de Dios,
lleno de la crueldad y enemistad de la serpiente contra todo lo que es bueno.

Entonces, el enemigo prevaricador obró a través de engañosas y seductoras tentaciones,
para mantener al hombre bajo ese dominio al que lo había arrastrado;
de modo que cuando algo se levantaba en el hombre y anhelaba al Señor,
el enemigo estaba listo para tragarlo y destruirlo con su boca devoradora.
Y habiendo ganado dominio sobre el hombre, lo hacía rendirse ante su voluntad,
y con su forma sutil de operar lo ha mantenido en las moradas terrenales,
y en los caminos mundanos a los que lo ha llevado,
y allí lo mantiene separado del Dios que lo creó,
conduciéndolo por las oscuras imaginaciones de la parte terrenal.

Aquí él engendra y produce cosas que son malas y pecaminosas,
de modo que el hombre se va deformando,
habiendo perdido la imagen pura en la que fue creado.
En efecto, se ha convertido en la naturaleza bestial de la serpiente,
y es impulsado y gobernado por ese espíritu inmundo,
que engendra obras de oscuridad y dirige al hombre a cometer pecados con avidez.

Así fue cómo el hombre perdió la autoridad en la que una vez gobernó sobre la creación,
y ha caído bajo el poder de la oscuridad.
La serpiente lo ha debilitado y ha puesto la creación sobre él,
llevándolo a cometer el mal en su uso de la creación. Y debido a que el
corazón del hombre ha descendido a la tierra y se ha sometido a ella,
es llevado cautivo por ella a voluntad de la serpiente.
Y así es como la borrachera y la glotonería,
el orgullo y la codicia han llegado a dominar al hombre.
El diablo lo mantiene cautivo en estas cosas, y él no sabe cuánto comer o tomar,
ni qué vestir, ni cuánta materia terrenal debería desear,
porque la serpiente ha llevado su corazón a codiciar el mal de manera tal,
que siempre está deseando, pero nunca está satisfecho.
Y aunque el hombre haya recibido de la creación lo
que es suficiente para su necesidad actual,
aun así desea recibir más. Sus deseos lujuriosos lo acosan constantemente,
de modo que nunca se contenta con lo necesario.
Por eso, cuando un hombre come y bebe lo que necesita y es fortalecido,
aun así la lujuria no es saciada,
y el diablo provoca a la voluntad para ir en busca de más;
y cuando el hombre le da cabida al deseo lujurioso y lo sigue,
también sigue al diablo que es el padre de él, y de esta manera sirve al diablo.
Y así, vencido por los deseos, permanece esclavo a ellos.
Su voluntad avanza en libertad carnal, y el enemigo lo incita al exceso,
sabiendo que sus deseos no serán saciados hasta que haya recibido tanto de la
creación como para privarlo del uso correcto de sus facultades naturales,
y convertirlo por completo a la naturaleza bestial de la serpiente,
que se regocija sobre él en ese estado.

En este lugar el diablo ejerce su dominio,
habiendo sometido al hombre tanto bajo su poder como bajo la creación,
sobre la que antes tenía dominio el hombre.
Por eso ahora el corazón del hombre codicia la bebida hasta que se emborracha,
y codicia la comida hasta que se abarrota.
Y estando la mente del hombre dirigida hacia lo de abajo,
Satanás lo guía a las partes más bajas de la tierra,
y allí engendra deseos aún más codiciosos tras las cosas terrenales.
Por eso el hombre desea lo terrenal y los beneficios que se obtienen de él;
y a medida que éstos crecen, el corazón se enamora más de ellos,
y la lujuria fervientemente ansía obtener un disfrute mayor.
El diablo lo convence de que aún no ha obtenido lo suficiente de las cosas que necesita,
y cuando finalmente obtiene una, entonces el diablo le tiene lista otra y se la presenta.
Así, el hombre tiene sed de esa nueva cosa, y anhela fervientemente disfrutarla; y así,
su deseo lujurioso no tiene fin.

De aquí se levanta todo engaño, fraude y estafa,
pues este deseo codicioso siempre busca la manera
de obtener beneficio propio y sacar alguna ventaja.
De modo que un hombre defrauda a otro,
y los hombres se traicionan y engañan unos a otros,
porque los deseos lujuriosos en los cuales obra el diablo codician una ganancia ilícita.
Ellos desean ser ricos, ser valorados entre los hombres,
colocarse en una posición de honor y dignidad en el mundo, etc.
Y cuando un hombre llega a ser escogido por encima de otros, aun así no se contenta,
sino que desea más honor, dignidad y ascenso.
Así los hombres alcanzan ese honor que es de abajo,
pero no comprenden el honor que es de Dios,
y entonces llegan a ser como bestias que perecen;
porque el honor de abajo sólo enaltece al hombre,
y lo exalta en el orgullo de su corazón. Y a medida que sus bienes terrenales se incrementan,
gana mayor estima y honor entre los hombres, de modo que los ricos son preferidos,
y los pobres subestimados y despreciados.
Y si a tal hombre no se le da el honor que espera, (inclinarse ante él,
halagarlo y quitarse el sombrero) entonces el diablo convierte su codicia en enojo,
envidia, malicia, odio, crueldad, venganza y maldad.

Todo esto es la obra del diablo,
donde el hombre (separado de Dios) se encuentra deseando y codiciando
y luchando por las riquezas y el honor y la gloria mundana,
buscando ser el mejor, escalando cada vez más alto para gobernar sobre otros,
con la expectativa de que todos se sujeten bajo su poder.
Pero ni el que gobierna, ni los que son gobernados,
están contentos en el lugar donde están,
sino que la lucha continúa con respecto a quién debería ser el mejor.
Y a partir de aquí surgen guerras y contenciones,
hombres destruyéndose y matándose unos a otros;
porque el diablo gobierna a través de la lujuria, incitando el enojo,
la malicia y la venganza.
¡Ay!
El diablo ha engendrado un reino de tinieblas en el hombre,
y allí se establece como príncipe y se enseñorea del hombre con sutileza.
Todo lo que desea lo realiza mediante la lujuria,
y bajo su poder el hombre está cautivo y comete muchos males.

Esta no era la condición del hombre en el principio, pero la serpiente lo ha deformado,
y ha engendrado en él muchos deseos lujuriosos,
de modo que él codicia con vehemencia la parte visible de la creación. Él ha
perdido su unión con el poder y la sabiduría pura de Dios en los que fue creado,
y se ha mezclado con cosas corruptibles, engendrando obras corruptibles.
Éstas oprimen la creación pura de Dios y la mantienen en esclavitud,
y diariamente incrementan el peso que está sobre ella,
así que toda la creación gime con dolores de parto,
pues el diablo y su obra se han levantado y esparcido sobre ella.
Por lo tanto, la avaricia, la embriaguez, glotonería, orgullo, envidia, malicia, ira,
enojo, mala voluntad, engaño, fraude, los ardides, el quebrantamiento de la tregua,
las acusaciones falsas, altanería, grosería, palabras ociosas, vana comunicación, burla,
reproche, afrenta, la adulación,
el deleite en los deportes y los placeres y los pasatiempos--estos
se han convertido en la vida misma del hombre,
y su deleite está diariamente en ellos.
Asimismo, lo separan del disfrute del Dios puro que lo creó,
que en Su sabiduría hizo todas las cosas buenas.
Nada de eso fue engendrado en la creación pura de Dios,
sino que todo ha sido producido por la serpiente a través de la degeneración del hombre.
Todo se ha levantado desde el principio a través de la sutil obra del enemigo,
pues él es el padre de esas cosas.
Y todos aquellos cuya vida está en esas cosas, o cuyo deleite está en ellas,
son sus hijos, y están separados de Dios y alejados de Su Vida.
Estos no pueden gustar las cosas buenas de Dios,
porque las corrientes del refrigerio puro de Dios están obstruidas, por lo tanto,
no pueden seguir su debido curso a través de las venas de la creación pura,
para vivificar al hombre interior y levantarlo.
¡Ay! El viejo hombre junto con sus obras detiene la corriente.
Adán se interpone,
obstruyendo el libre recorrido del amor y de la vida invisibles del Creador,
en los que el hombre tenía su comunión y satisfacción antes de la transgresión.
