== Capítulo IV. El Camino y las Obras del Hombre en la Separación

Habiendo perdido el poder y la sabiduría en los que fue creado,
y con los que una vez gobernó sobre las criaturas,
y habiendo sido arrastrado hacia abajo por la fuerza del engaño,
el hombre ahora se encuentra degenerado del camino de santidad y de las obras de justicia,
y es guiado en los caminos de oscuridad.
Aquí está su rumbo,
en la parte visible de la creación y en el camino contaminado de sus propias invenciones,
el cual es ancho y lleva a la destrucción. Aquí él desea y aquí él corre,
con la serpiente apresurándolo a avanzar rápidamente,
_no sea que en algún momento se detenga y considere el mal de su camino y se aparte de él._
Y de esa manera, es llevado hacia una mayor separación de Dios,
y arrastrado en el camino torcido, donde es engendrado un deleite por caminar en él,
siendo seducido por los diversos objetos y apariencias que la serpiente le presenta.
Sí, ahora él encuentra su propósito, amor y deleite en todas esas cosas,
amando sus propios placeres y ganancias más que a Dios.
Y la obra de la serpiente es hacer que esto le parezca correcto,
cubriendo tales cosas con un velo engañoso,
a fin de que los hombres permanezcan ciegos y no vean las cosas tal como son en la luz.
De ahí que el borracho diga:
"`Mi camino es el amor a mis amigos;`" y el hombre avaro diga:
"`Mi camino es la providencia y la prudencia;`" y el hombre altivo diga:
"`Mi camino es ser atractivo y agradable;`" y el engañador diga:
"`Mi camino es el ingenio y la eficacia;`" y el burlón insensato diga:
"`Mi camino es el gozo y la alegría.`"
De este modo ciega y guía el diablo a cada hombre, de manera tal,
que no puede ver dónde ha sido engañado, sino que camina y avanza hasta llegar al fin,
donde le está preparado el pozo.
Este es el camino por el que caminan la mayoría de los hombres,
donde el hombre busca satisfacer la carne con sus afectos y deseos.

Así pues, todo mal procede del corazón engañoso, donde la serpiente engendra su imagen.
Porque de allí proceden el asesinato, adulterio, avaricia, embriaguez, orgullo, envidia,
malicia, junto con todas las otras cosas que son malas y que separan al hombre de Dios.
Y en este estado ningún hombre puede complacer a Dios, ni hacer nada bueno,
pues todas sus obras provienen de la fuerza y poder de las
tinieblas que reinan libremente en la parte carnal,
y nunca cesan de producir deseos lujuriosos en la carne.
Y cuando el hombre se une con la tentación (que la
serpiente ofrece a la concupiscencia que ha engendrado),
entonces el pecado es concebido; y cuando el pecado es concebido y dado a luz,
entonces la muerte viene sobre el hombre.
Pues escrito está: "`el pecado entró en el mundo, y por el pecado la muerte.`"^
footnote:[Romanos 5:12]

Porque la paga del pecado es muerte, y mientras el hombre viva según la carne,
permanece en la muerte; porque todas sus obras son corruptas e impuras,
y el Dios puro no se complace en ellas.
_Y mientras el hombre ande en la carne, permanece bajo condenación;_
la ira y la maldición están sobre él,
y la mano del Señor está contra él. Y ya sea la profanación
explícita o la profesión de santidad,
si surge de las tinieblas y sigue su curso en la parte carnal de la creación,
el Espíritu lo condena y juzga todo.
Sí, el que anda en la carne y satisface el deseo que la serpiente ha engendrado,
será vencido al final por la muerte.
Tal hombre debe morir porque sus obras son carnales.
Por eso Pablo dice: "`la muerte pasó a todos los hombres, por cuanto todos pecaron.`"^
footnote:[Romanos 5:12]
Y en tanto que el camino del hombre esté en la parte carnal,
y sus obras nazcan de la concupiscencia de ella, la muerte permanece sobre él,
y muere la misma muerte que el primer hombre en la
transgresión. Porque no hay acepción de personas,
sino que "`todos los que sin ley han pecado, sin ley también perecerán;
y todos los que bajo la ley han pecado, por la ley serán juzgados.`"^
footnote:[Romanos 2:12]
Así se probarán el camino y la obra de cada hombre, y será recompensado según lo que haga.
El que siembra para la carne, de la carne cosechará corrupción,
y en ese estado no puede heredar incorrupción. De modo que el borracho, el blasfemo,
el mentiroso, orgulloso, avaro, jactancioso, envidioso, iracundo, burlón insensato,
hablador de vanidades, fornicario, asesino,
junto con todo engañoso e hipócrita profesante de piedad que carece del poder de Dios,
no pueden heredar el Reino de Dios, puesto que están en la naturaleza impura;
sus caminos y sus obras están en la carne.

El "`que vive conforme a la carne, morirá.`"^
footnote:[Romanos 8:13]
No puede heredar el reino de Dios, sino que permanece separado del Dios que lo creó,
y en esa impureza que no le permite acercarse a Él. Ciertamente,
la justicia y la injusticia no tienen comunión la una con la otra,
y el hombre no puede entrar al paraíso puro de Dios con una vestimenta contaminada,
ni gozar de Su presencia pura,
sino que está separado lejos de Él. Aquí se encuentra sumido en una lamentable miseria,
en gemidos y suspiros en las partes más bajas de la creación visible,
donde la serpiente es el príncipe y gobierna sobre
él. Y mientras alguno viva y camine en la carne,
y produzca sus obras, permanece como un hombre degenerado, a gran distancia de Dios.
En éstos, la parte terrenal ha crecido sobre ellos y ha hecho una separación,
la cual agobia a la Semilla pura que permanece en esclavitud,
bajo una mezcla de las propiedades caídas que están fuera de orden.

Por lo tanto, es necesario que cada hombre considere sus caminos y obras,
y que rápidamente lo tome en serio, considerando que todos han pecado,
que ninguno puede ser salvo _en_ su pecado, ni complacer a Dios en la carne,
y que la carne y la sangre no pueden heredar Su Reino.
Porque todos los que viven y andan en la carne permanecen separados de Dios,
donde Su ira es experimentada y Sus juicios son ejecutados, sin acepción de personas.
