== Capítulo V. Qué es lo que Convence al Hombre del Mal

El hombre,
arrastrado a la desobediencia mediante la sutil obra del príncipe de las tinieblas,
se volvió un transgresor del poder puro y de la sabiduría del Creador.
Salió del bien en el que fue creado, y entró en el mal tras obedecer al tentador.
Y tras comer de la mezcla en la que cayó,
"`todo designio de los pensamientos del corazón era de continuo solamente el mal,`"^
footnote:[Génesis 6:5]
y el mal obró cada vez más para ganar dominio sobre el bien;
de modo que el hombre fue despojado de toda gloria y alejado de la Vida santa.
Sin embargo, la Semilla de Dios conservó Su propia pureza,
y Su santo carácter y propiedad sin mezcla alguna;
ésto no fue extinguido por la caída del hombre.
Aunque el hombre salió de ella, y no permaneció en Ella,
aun así la Semilla conservó Su pureza;
y la Luz pura brillaba en la conciencia del hombre (a través del amor eterno de Dios),
para convencerlo de los malos caminos y de las obras en
las que había caído. La luz resplandecía en las tinieblas,
manifestaba las obras de las tinieblas, y convencía al hombre del mal de ellas.

Por medio de la luz de esta Semilla,
Adán fue convencido de su transgresión y por eso se escondió de Dios.
Por ella Caín fue convencido de que había asesinado, y clamó a causa de su castigo.
Por ella Saúl fue convencido de su crueldad, y le dijo a David:
"`Más justo eres tú que yo.`"
La luz de esta Semilla santa de vida resplandece en amor,
y es hecha manifiesta en las conciencias de los hombres caídos,
habiendo sido dada gratuitamente por Dios para buscar al hombre en su
estado caído. Dondequiera que la sutil serpiente haya arrastrado a las
mentes de los hombres y engendrado su imagen,
allí escudriña y resplandece la Luz para convencer
y reprobar al hombre en su propia conciencia,
de modo que no puede ocultar sus secretos ni tesoros.
Porque la Luz resplandece en las tinieblas, aunque las tinieblas no la comprenden,
y con Su resplandor puro descubre tanto las obras de las tinieblas,
como al príncipe de las tinieblas, poniendo de manifiesto sus obras secretas,
y _dejando que el hombre vea y sienta que es un extraño para Dios,
y que está lejos de Su vida pura,
sirviendo a un espíritu que está en enemistad contra Dios._

De este modo, el amor de Dios se ha manifestado mediante la luz de la Semilla de Vida,
la cual ha sido la misma a través de todas las generaciones,
y por medio de Su naturaleza pura,
ha descubierto la enemistad del corazón engañoso del hombre,
junto con todas sus obras fraudulentas.
Ha sacado a la luz cosas ocultas, mostrando al hombre cómo se ha empleado su mente,
y hacia qué se ha inclinado,
y en pos de qué ha codiciado su corazón. Siempre
que los deseos han prevalecido y engendrado el mal,
la Luz ha estado cerca para convencer al hombre de ello y para reprenderlo por ello.
Y cuando el hombre ha hecho bien, por la misma Luz se siente justificado y aprobado,
y se le deja ver su aceptación.

De esta manera el Señor Dios espera para poder mostrar Su misericordia,
y a través de todas las generaciones se ha manifestado Su misericordia,
para restaurar con misericordia la creación a su santo orden,
y sacar al hombre del poder de las tinieblas.
Él busca liberar al hombre de la esclavitud,
para que ninguna cosa corruptible (en la que ha caído
por desobediencia) permanezca sobre él,
sino que sea quitada y removida,
y para que el Cordero (que fue inmolado desde el principio del mundo^
footnote:[Apocalipsis 13:8]) pueda ser vivificado y levantado en él,
y llegar a Su dominio puro sin mancha o defecto alguno.
Pues Él es más puro como para mezclarse con cualquier cosa corruptible, y en efecto,
las cosas corruptibles oprimen Su tierna Vida en el corazón,
y Él soporta el peso de ellas.
Con mucha paciencia sufre bajo ellas, el Justo por el injusto,
para poder llevar al hombre de nuevo a Dios,
y restaurar la creación a su orden puro donde antes descansaba con Dios,
siendo movida en el poder y la sabiduría de Dios.

Esta Vida en el interior es Cristo, la Semilla santa, en quien el pacto permanece firme,
a quien son hechas todas las promesas,
el Único en quien son sí y amén. Desde el principio,
esta Semilla ha sido revelada para herir la cabeza
de la serpiente y para destruir sus obras.
Ha estado obrando en todas las generaciones,
incluso en las propiedades caídas de la creación visible,
para buscar y encontrar al hombre en todas sus transgresiones
y en su secreto andar por los caminos de tinieblas.
Pues ella manifiesta los malos deseos del hombre y lo convence en su propia conciencia,
cada vez que la codicia extiende su mano para apoderarse de lo que es malo.
Esto lo ha hecho en las generaciones anteriores, y esta cualidad pura no cambia.

Así es como el hombre, al ser convencido por la Luz,
se convierte en una criatura sensible,
y en su propia conciencia sabe que no debe hacer el mal,
pues ve el mal en sí mismo antes de cometerlo.
Y cuando la tentación lo arrastra y prevalece sobre él,
entonces es capaz de ver que se acerca más al mal.
Por lo tanto, todos los hombres quedan sin excusa, porque el mal les es hecho manifiesto,
y son convencidos en sus propias conciencias.
Y todo el que corre hacia el mal, o es hallado en algo malo, ya sea de pensamiento,
palabra u obra,
transgrede contra la Luz que resplandece en amor desde la Semilla santa de Vida,
y que exhibe y convence al hombre en su propia conciencia.

Aquí el hombre está en la caída,
donde todas las propiedades de la creación entera están fuera de orden,
y su corazón codicioso persigue con ansias las cosas malas.
Sin embargo, dondequiera que corra en la caída,
o cualquiera que sea el camino por el que la serpiente lo dirija,
la Luz revela y manifiesta el mal en su propia conciencia.
Y así, el borracho es convencido de que sus obras son malas,
y de que permanece en la inmundicia de ellas;
y eso que lo convence es la Luz en su propia conciencia, la cual es pura,
sin ninguna mezcla de maldad.
El hombre engañoso es convencido de su injusticia;
y eso que lo convence es la Luz de Cristo, que es justa y santa.
El mentiroso es convencido de que sus obras son malas, y lo percibe en secreto,
incluso mientras la mentira permanece aún en su pecho.
Y eso que le permite ver su mentira antes de ser dicha y lo convence de ella,
es la Luz de Cristo en su propia conciencia,
la cual es verdad y no tiene ningún engaño en ella,
y se manifiesta para destruir toda mentira, y al padre de las mentiras.
En realidad, no hay nada que la serpiente produzca,
que no sea descubierto y mostrado por la "`luz verdadera,
que alumbra a todo hombre que viene a este mundo.`"^
footnote:[Juan 1:9]

Porque la serpiente se ha sentado en la mezcla de la parte terrenal corruptible,
entre las propiedades caídas, y allí tiene su curso y su camino en las tinieblas.
Ahí produce un corazón engañoso,
del cual procede toda clase de maldad que contamina al hombre.
Y así ha producido un cuerpo de pecado,
y ha obrado a través del engaño en las propiedades corruptibles,
para arrastrar la mente del hombre en pos del pecado.
Ahí también engendra el amor y el deleite en el pecado,
provocando deseos codiciosos para perseguirlo con avidez,
deseos que nunca pueden ser satisfechos.
Porque mientras el hombre corre en este camino ideado por la serpiente,
y la sigue en su guía y codicia sus tentaciones, lleva una gran carga sobre sí mismo,
tiene muchos problemas,
y encuentra que hay algo en el fondo que gime bajo el peso de esos deseos
y pecados que la serpiente ha engendrado en el cuerpo de pecado.
Pues lo que gime en el interior es de una naturaleza contraria; no es corruptible,
sino que se siente oprimida y cargada por toda la corrupción. Es
la serpiente la que ha engendrado corrupción desde el principio,
y en ella ha arrastrado la vida del hombre,
de modo que toda la creación ha sido sacada de su santo
orden y por ello sufre como con dolores de parto,
y así, todo el curso de la naturaleza arde en fuego.
De esta manera fue despojado el hombre de ese entendimiento puro en el que fue creado,
y en el que inicialmente discernía y conocía toda la creación
cuando ella estaba en el poder y sabiduría de Dios.

Pero, aunque el hombre está tan degenerado, y ha perdido su entendimiento original,
y la serpiente lo ha arrastrado a las propiedades
caídas de la parte corruptible de la creación,
en donde se ha convertido en una bestia sin entendimiento,
sin conocer al Dios de poder y sabiduría, ni el orden de Su creación; aun así,
en este estado degenerado (en el que se puede decir que el hombre está separado
y alejado de Dios) permanece una Semilla pura y santa que mora dentro de él que,
en su luz pura y resplandor, alcanza el corazón engañoso del hombre.
Y con Su luz y resplandor,
esta Semilla verdaderamente expone todo mal que se genera en el corazón engañoso,
y convence al hombre del mal, ya sea de pensamiento, palabra u obra.
Cuando el corazón codicia el enojo, y el enojo se enciende en el pecho del hombre,
entonces la luz lo manifiesta y convence al hombre
de que está envuelto en algo que es malo.
Y todo lo que es engendrado por la serpiente,
y luego concebido en el corazón engañoso del hombre, la Luz lo descubre;
y no hay nada que pueda impedir que atraviese y escudriñe las propiedades
caídas para descubrir al hombre--quien se ha convertido en un mal
obrero--y convencerlo de todas sus malas obras.
Porque el hombre no puede escapar de la Luz, aunque ande en medio de la oscuridad,
y elija su camino en los lugares tenebrosos de la tierra y siga el camino de la serpiente,
produciendo las obras de su engendramiento.
La Luz lo encontrará incluso allí, y el hombre será convencido por ella,
y el pecado será puesto ante su propia conciencia para que pueda ver sus obras malas,
las cuales lo separan de Dios y lo mantienen alejado de la Vida santa.
