[short="Capítulo VI -- Cómo Se Encuentra el Hombre en el Estado de Convicción"]
== Capítulo VI. Cómo Se Encuentra el Hombre en el Estado de Convicción, y las artimañas de la serpiente.

Cuando un hombre en su condición caída es vencido por el mal,
de modo que su corazón engañoso da a luz un nacimiento engendrado por la serpiente,
entonces la Luz pura se le acerca para convencerlo, y permitirle ver que es un malhechor,
y que está atrapado en lo que no es bueno.
Y cuando la luz lo expone y lo convence de esa manera,
le hace ver verdadera y claramente que su camino no es correcto,
que sus obras no son aceptadas por Dios, y que si continúa sin arrepentirse,
perecerá. Y bajo esta misma luz, el hombre ve que su conciencia está contaminada,
que hay inmundicia sobre él, y que su corazón no es recto,
sino que está lleno de engaño. La mayoría de los hombres reconocerán esto en palabras,
admitiendo que tienen un corazón engañoso del que proceden muchas cosas malas,
y que son malhechores y hombres pecadores.
Sí, cuando la luz alcanza al hombre y lo convence de su maldad, incluso un borracho,
un mentiroso y un blasfemo harán tal confesión,
porque Dios deja sin excusa a todo hombre.
Él conoce y ve todo el mal, y lo muestra por medio de la Luz verdadera de Cristo,
la Semilla de Dios,
que ve a través de todas las propiedades de la creación
visible y manifiesta cada senda tenebrosa.

Y esta Luz ha estado en el hombre desde que el aliento de Vida fue soplado
en él. Y aunque la caída ocurrió en el hombre por la astucia,
y cayó en la mezcla de las propiedades de la creación visible, a pesar de eso,
la Luz misma que fue soplada en la vida,
mediante la cual el hombre se convirtió en un alma viviente,
no fue extinguida por su caída,
ni su propiedad cambió cuando el hombre cayó en la mezcla.
No, la Luz conservó su naturaleza pura y santa,
aunque el hombre fue incitado a alejarse de ella, y cayó en el mal,
y así comenzó a morar en la muerte.
Esta Luz pura de Vida ha sido la misma a través de todas las generaciones,
y por Su cualidad escrutadora, ha revelado todo el mal que tiene o comete el hombre.
Nunca ha cambiado en propiedad o cualidad, sino que ha continuado pura, santa,
justa y humilde, tal como es hoy; pero en la caída,
el hombre se convirtió en algo ajeno a Su naturaleza, algo contrario a Ella,
de manera que la Luz descubre, testifica en contra,
y reprueba todas las maquinaciones que el diablo
ha engendrado en el hombre desde el principio.
Y aunque la serpiente ha ganado dominio sobre el hombre,
y engendra sus malas obras en él, aun así la Luz continúa descubriendo esas cosas,
y permite que la conciencia del hombre las vea;
porque la Luz se manifiesta en la conciencia para herir la cabeza
de la serpiente y para destruir su obra en el hombre.

Este testimonio es verdadero--aunque la astucia no puede recibirlo--y
todos los que alguna vez se han familiarizado con la Semilla de Vida,
jamás han testificado de otra cosa, ni predicado otro evangelio;
de modo que el evangelio de la Simiente predicado a Abraham,
ha sido y es el mismo a través de todas las generaciones.
Porque la santa Semilla nunca cesa de buscar al hombre
que ha caído en la mezcla de propiedades,
y allí lucha con él convenciéndolo y reprobándolo,
para que el hombre no permanezca en la muerte, sino que se levante y la siga,
y llegue a heredar la vida.
Y este es el amor de Dios, que fue, es y ha de venir; que no quiere que ninguno perezca,
sino que todos se vuelvan y vivan.
Y aunque Su amor se manifiesta gratuitamente,
y encuentra al hombre en su estado desordenado,
caminando según sus afectos desordenados y rebeldes que la serpiente ha engendrado,
a pesar de ello, el hombre (en su mayor parte) no recibe la invitación del amor de Dios,
ni se vuelve a las correcciones de la Luz.
En lugar de eso, ama sus malas obras más de lo que ama la Luz,
y no se acercará a la Vida,
sino que es retenido por la astucia de la serpiente
en la mezcla de las propiedades caídas,
y allí se deleita más en el mal que en el bien.
Y por esta razón la Luz lo condena,
y el malhechor no puede escapar de la Luz que lo convence de sus malas obras,
sino que cualquier cosa que desee y en la que encuentre su vida,
la Luz se lo manifestará, por muy secreto que sea,
porque ningún hombre puede ocultarse de la Luz.
Y aunque la serpiente engendra muchas cosas malas,
e incita al hombre más y más hacia una conciencia mala,
y cautiva la mente del hombre en ella, aun así,
la Luz no cesa de llevar testimonio contra el hombre en su maldad,
y de convencerlo de sus malas obras.

De esta forma, es consciente el hombre de su propio pecado y mal,
pero al no volverse a la Luz cuando es convencido por ella y cuando percibe su mal,
continúa morando en el mal.
Y como la serpiente sigue ejerciendo dominio sobre él,
lo persuade en su mente de que esta Luz que lo convence no es suficiente para salvarlo.
Y de ese modo le genera incredulidad, y aleja la mente de la obediencia a la Luz,
o de la espera en ella para conocer el poder de Su operación. Y el hombre,
siguiendo el consejo de la serpiente, es arrastrado cada vez más lejos de la Luz,
y no creerá que ésta sea capaz de salvarlo,
ni se volverá a la Luz cuando sea convencido por ella,
sino que la llamará "`luz natural`", o "`conciencia natural`",
o "`la parte más sensible del hombre natural,`" sin creer que viene de Dios,
ni que es capaz de salvar o de dar vida cuando es obedecida.
Y a muchos se les ha dicho que esta obra de la Luz, no es la obra del Redentor,
o del Mediador, o del Intercesor,
pues esos nombres (dicen) solamente le pertenecen
al hombre Jesucristo que murió en Jerusalén,
y que los hombres sólo deben basar su fe en la obra
histórica y externa que ya ha sido hecha por ellos,
y que así, sus pecados no les serán imputados,
aunque vivan en ellos y sigan cometiéndolos.

La serpiente ha engañado a muchas personas de este modo,
engendrando incredulidad en la Luz que brilla en sus propias conciencias,
mostrándoles su pecado y convenciéndoles de ello,
y engendrando también una fe imaginaria en que serán
salvados por el Cristo que murió en Jerusalén,
aunque continúen viviendo en sus pecados.
Así es como el pecado es _manifestado_ en muchos, pero no es _destruido,_
y la serpiente convence al hombre de que no puede
ser de otro modo mientras lleve un cuerpo natural.
"`Porque,`" dice la serpiente, "`la naturaleza del hombre es propensa al pecado,
y nadie puede librarse de ella hasta que su cuerpo sea sepultado.`"
De esta manera la serpiente produce incredulidad en la Luz de Cristo,
y engendra una fe falsa en un Cristo meramente externo,
pero no en Su obra interna en el hombre.
Entonces, muchos creen que aunque gasten su tiempo pecando en este mundo,
aun así serán salvos en el porvenir.
Y al no obedecer la Luz de Cristo, no llegan a conocer Su vida y virtud, ni Su salvación,
mediación e intercesión, sino que permanecen en la mezcla de las propiedades caídas,
sin experimentar ningún cambio producido en ellos por el poder de Cristo.
En este lugar, los hombres son convencidos por la Luz,
ya que ven las cosas que son malas, pero como no creen en la Luz,
continúan en el mal y no son verdaderamente convertidos.
