[short="Capítulo VII -- El Hombre en el Estado Convertido"]
== Capítulo VII. Cómo Se Encuentra el Hombre en el Estado Convertido, y las artimañas de la serpiente.

Así pues, la creación pura se encuentra bajo esta dura labor
y dolor por el desorden de las propiedades caídas,
en las que la serpiente se ha sentado y se ha exaltado
a sí misma sobre todo lo que se llama Dios.
En este lugar mantiene al hombre en un estado separado de la Vida de Dios,
donde lo cubre la sombra de muerte, y una aguda aflicción y dolor están sobre él,
oprimiéndolo fuertemente y haciéndolo lamentarse día a día,
de modo que en ocasiones comienza a considerar su estado
y condición. Y mientras considera estas cosas en su mente,
la Luz pura alumbra en su conciencia, mostrándole cuán lejos está del Dios puro,
y cuán ajeno es a Su Vida,
y cuán grande es el cuerpo de corrupción que está
dentro de él que causa su separación de Dios.
Y cuando esto le ha sido manifestado,
es golpeado con el sentido de su miserable condición,
y es llevado a un estado de espera para ver si puede
encontrar algo que lo ayude o lo alivie.
Entonces, a veces siente algo dentro de sí mismo que clama a Dios,
de quien ha estado separado debido al cuerpo de pecado,
y surge una pregunta acerca del camino para llegar a Él,
y cómo puede ser liberado de esas cosas que lo separan de Dios.
Y mientras se mantiene en esa búsqueda seria, la Luz resplandece más y más,
dando lugar a verdaderos hallazgos.
Porque en la luz el hombre comienza a percibirse sobremanera pecaminoso,
y pone en duda muchas cosas en las que se ha visto envuelto,
considerándolas ser de una naturaleza impura.
Y así comienza a detestar tales cosas,
y ya no puede deleitarse en ellas como solía hacerlo en el pasado,
sino que comienza a aborrecerlas, y a esperar en la Luz que las expuso,
para ver si puede ser preservado de ellas; pues a partir de ese momento ve que son malas,
y que lo contaminan, y que son una carga pesada, y un doloroso yugo sobre él. Entonces,
al prestarle atención a la Luz y obedecer lo que ella manifiesta,
recibe una medida de poder contra esas cosas, y obtiene cierta victoria sobre ellas.

Ahora bien, el hombre en este estado puede tener todavía poco conocimiento de la Luz,
y sin embargo,
en la medida que es fiel en volverse a ella--según Su manifestación
y el conocimiento que proviene de ella,
volviéndose del mal a la Luz--en esa medida experimenta
una verdadera conversión. De este modo,
el hombre deja gran parte de la vanidad en la que ha vivido,
y se aparta de los caminos impuros de la corrupción,
y esas cosas que alguna vez fueron agradables para él, ahora le resultan odiosas.
Por lo tanto, deja la embriaguez,
y el exceso de comida y bebida a los cuales se había acostumbrado,
y también toda mentira y lenguaje obsceno y ropa a la moda,
en lo que había vivido y se había deleitado.
Y lo que produce ese cambio y lleva al hombre a la moderación,
es la Luz pura de la Semilla santa de Cristo,
que nunca consiente ni encuentra placer en el hombre
cuando está involucrado en cosas que son malas,
sino que se esfuerza siempre por convencerlo del mal.
Y a medida que él obedece la Luz de Cristo,
se echa un cordel de amor a su alrededor para atraerlo,
y el Señor continúa obrando la conversión del hombre.

Ahora bien, muchos han llegado a esta condición,
habiendo sido convencidos por la Luz,
y habiendo sido convertidos también de muchas cosas malas y profanas, y sin embargo,
nunca han sido completamente liberados de las ataduras de la muerte,
sino que han sido mantenidos prisioneros en la casa de esclavitud.
Pues la serpiente obra engañosamente para mantener
al hombre en una forma de profesión religiosa,
en la que camina como un hombre sobrio y moderado, modifica sus malos caminos,
aparenta estar bien, y sin embargo, descuida la Luz en su conciencia,
obteniendo contentamiento de aquello que profesa con palabras.
Con esta imagen falsa que la serpiente ha engendrado en la imaginación,
ha engañado a muchos, y los ha llevado a desviarse del camino correcto,
alejándolos de la Luz que una vez los convenció y apartó de muchos males.
Y personas como estas, a menudo se convierten en las mayores enemigas de la Luz,
porque es difícil renovar a alguien que una vez fue iluminado,
y que por un tiempo estuvo vuelto y experimentó el inicio de la obra de Dios,
pero que después se apartó de ella.
Éstas ciertamente se endurecen,
y así apagan y detienen el poder antes de ser completamente
regeneradas o de llegar a experimentar el nuevo nacimiento.
Sí, la serpiente ha engendrado muchos falsos nacimientos y semejanzas,
cuya deformidad e impureza han estropeado la belleza del verdadero nacimiento celestial.
Y a partir de aquí han surgido muchas religiones y grupos,
que niegan muchas cosas malas y profanas, y que profesan las Escrituras,
y las multitudes quedan satisfechas con esta apariencia externa.

Sin embargo, la Luz de Cristo en la conciencia del hombre,
no deja de buscar a los que están en este estado profesante;
pues aunque no andan como los ebrios o como los que maldicen,
la luz les muestra que son practicantes de culto
voluntario y que son complacientes con los hombres,
y testifica contra su doble ánimo,
inconstancia e hipocresía. Porque aunque parece haber una gran
diferencia entre la corrupción explícita y la apariencia de piedad,
aun así, éstas son engendradas en el mismo vientre,
y reciben su alimento a partir de la mezcla de las propiedades
caídas que permanecen en el caos y la confusión,
y tienen a Babilonia la Grande como su madre.
De modo que, tanto la corrupción explícita como la profesión de piedad sin el poder,
están contaminadas y ambas son condenadas por la Luz que es pura.

Este es el lamentable estado de muchos;
y muchos han llegado muy lejos sin haber podido avanzar,
porque han descansado en una profesión formal en la que no hay alivio ni satisfacción,
y no han soportado la lucha de la aflicción tras haber sido iluminados,
sino que se han apartado de la puerta angosta que conduce al estanque de sanidad.
No, no esperan pacientemente hasta que Él llegue y les dé poder para tomar su lecho y andar,
sino que se desvían (aunque débiles y lisiados) al camino ancho,
evadiendo la cruz y sanándose a sí mismos con una libertad falsa.

Sin embargo,
en esta tierra extranjera todavía hay algo dentro del hombre que anhela su tierra natal,
donde no hay mezcla corruptible,
y la Luz no deja de escudriñar el corazón engañoso del hombre,
del que proceden tanto la corrupción como la profesión de piedad.
Y mediante el resplandor de la Luz, los corazones de algunos se abren y llegan a ver,
que no son rectos delante del Señor,
y que sus corazones no se alinean con su profesión externa,
sino que la humildad fingida y la hipocresía moran en su interior,
por lo que son heridos y corregidos por el Señor. Luego,
éstos se dan cuenta de que son verdaderamente miserables, débiles y corruptos,
y ven que tanto su justicia como su inmundicia proceden
de la mezcla de las propiedades caídas,
y son conscientes de la mano correctora del Señor. Y aunque han negado mucha corrupción,
y han hecho una gran profesión de piedad,
perciben que están alimentándose diariamente de una fuente seca.

Y si éstos comienzan a considerar la Luz y a esperar en ella,
ésta se levanta para destruir sus fortalezas,
y para llevar a la ruina sus ciudades amuralladas,
reduciendo a nada la gloria de su apariencia, manchando su orgullo,
y mostrándoles que las prácticas externas no pueden producir contentamiento interno.
Y así es como la Luz los persigue, les inflige muchos azotes,
y pone sus pecados en orden delante de ellos,
permitiéndoles ver el gran cuerpo de pecado, por el cual claman al Señor en su miseria:
"`¿Quién me librará?`" Y llegan a ser conscientes de su propia insuficiencia,
y de que sin Cristo nada pueden hacer,
y de que todas las cosas externas no son más que consoladores molestos
que carecen de poder para ayudarlos en tiempos de necesidad.

Ahora, si éstos continúan inclinándose a la Luz que resplandece en el interior,
y son diligentes en escucharla, obedecerla y volverse a ella,
considerando sus reprensiones y esperando sentir sus movimientos,
entonces la Luz los convencerá de más maldad.
Y en la medida que se sometan para obedecer y negar la maldad de la que han sido convencidos,
en esa medida _la Luz destruirá el mal, apartándolo de ellos,_
y de esta manera llegarán a estar satisfechos de que ciertamente
dicha Luz es la verdad de Dios y el camino por el que deben andar.
Cuanto más esperan sentir sus persuasiones y dirigen sus rostros a Ella,
_más engendra una voluntad de rendirse y seguirla,
de manera que los hombres no sólo son convencidos, sino convertidos,_
y vueltos tanto de la corrupción común como de cada apariencia falsa de piedad,
siguiendo la Luz y rechazando toda maldad que la Luz descubre.
Porque bajo la guía de la Luz,
el hombre se mantiene bajo la cruz contra su propia voluntad corrupta,
y aprende a andar por el camino angosto,
sintiendo algo del poder del Señor obrando en el interior para crucificar
y eliminar las pasiones carnales que han hecho guerra contra su alma,
llevándolo a una medida de alivio, y quitándole de encima un gran peso doloroso para él.

Y cuando la Luz encuentra tal lugar en el hombre, y el hombre se vuelve a ella,
de modo que no puede permanecer más ni en la corrupción ni en la apariencia de santidad,
sino que va tras la Luz para salir completamente de la mezcla de
las propiedades caídas y entrar al santo orden de la creación pura,
entonces la serpiente lucha con sutileza para mantener
al hombre con cierta medida de mezcla,
para conservar dominio sobre él, aunque sea en algunas cosas,
y así no permitirle ser completamente libre.
Aquí, aunque muchos están convencidos de ciertas verdades,
y han llegado a negar muchos males, sin embargo,
a menudo se atascan en el nacimiento y no llegan
a sentir una verdadera libertad obrando en ellos,
sino que siguen padeciendo dolores de parto, clamando por el día de victoria.
Sí, la serpiente ha engañado a muchos que han sido convertidos y convencidos,
y que han tenido verdaderas revelaciones y claros hallazgos en la Luz;
pero al no ser vigilantes, la serpiente los ha engañado (así como engañó a Eva),
tentándolos con el mismo fruto y prevaleciendo sobre ellos,
al arrastrar sus mentes para que busquen satisfacer, en su propio afán,
el deseo humano de conocer la verdad de Dios.
Esto le cierra el vientre a la Vida que está siendo formada en el interior,
porque cuando los hombres están en esta condición, huyen de los juicios de Dios,
rechazan la cruz, y crecen en falsas libertades que producen esclavitud.
Y aunque confiesan y profesan la verdad, aun así,
la Semilla yace en cautiverio bajo sus mentes envanecidas
que la serpiente ha llenado de conocimiento,
y bajo un nacimiento falso que ella ha engendrado.
De modo, que la cerviz de estos hombres se vuelve progresivamente rígida,
sus corazones se endurecen, y no se inclinan ante el Señor ni se someten bajo Su poder.

Porque aunque un hombre haya podido ver la Verdad en la Luz,
cuando la mente carnal se llena de ese conocimiento, echa raíces en la parte terrenal,
y lo terrenal comienza a crecer y a extender sus
ramas en una hermosa apariencia de piedad.
Y aunque este cuerpo terrenal ha sido engendrado
y alimentado en la mezcla de las propiedades caídas,
y lleva sobre él un tinte de la Verdad proveniente de la Luz (tal
como el plomo puede ser cubierto con una capa delgada de oro puro),
y parece ser extremadamente glorioso, aun así, no es la gloria del Hijo unigénito.
Entonces, la serpiente antigua se esfuerza por alimentar este nacimiento,
para que crezca en fuerza y llegue a ser como un hombre alto y fuerte,
creciendo en altura como los cedros del Líbano,
y en conocimiento como las encinas de Basán. Y bajo
este alto y glorioso crecimiento en conocimiento,
la pequeña y jadeante Semilla es ahogada, angustiada y oprimida,
luchando todavía en mansedumbre y humildad para derribar
los altos cedros y humillar las fuertes encinas.
Pero los altos cedros se niegan a perder su gloria,
y las encinas a desprenderse de su fuerza,
manteniéndose firmes y resistiendo obstinadamente a la tierna Semilla,
y rechazando la palabra que los reprende.
Porque el alto cedro dice: "`¿Quién me señoreará?`" Y la encina testaruda dice:
"`¿Quién me hará doblar rodilla?`"
Y así, pisotean a la inocente Semilla como algo de poco valor,
y permanecen en la mezcla donde no hay una separación pura,
y donde la escoria y el estaño no perdurarán en el horno,
ni permanecerán en el Día de Su venida.
Porque la serpiente siempre ha obrado secretamente contra la Semilla de Vida,
que se manifiesta para herir su cabeza y destruir su obra.
Y aunque un hombre pueda haber seguido la Luz negando al
yo y tomando la cruz diaria contra las muchas modas,
costumbres y tradiciones, aun así,
la Semilla todavía puede continuar encerrada en el vientre por no haber sido liberada.

Pero el verdadero nuevo nacimiento o regeneración, procede de un vientre santo,
y es engendrado en el horno sin mezcla alguna de la parte terrenal.
Y cuando nace, cambia por completo al hombre, y lo redime perfectamente del mundo,
siendo alimentado por los pechos de la Vida santa;
y así crece en la naturaleza y en el poder puros de la Vida,
que hacen guerra y vencen a la serpiente y su poder.

Por tanto, que todos los cedros altos y las encinas fuertes,
consideren estas cosas y se humillen y se postren, porque deben caer y ser quebrantados,
y la inocente Semilla debe reinar por encima de todo porque es pura y sin mezcla.
Asimismo, consideren todos los que han gustado del verdadero poder,
y han conocido algo de su obra,
pero han regresado a la necedad o se han elevado por el aire,
y ahora defienden su libertad carnal como algo natural de la creación visible,
y se atreven a decir, que aunque viven en tal libertad,
ésta no contamina al hombre interior,
ni sienten reprensiones por sus obras humanas y carnales,
sino que permanecen justificados delante del Señor en su hombre interior; yo digo,
que todos éstos sepan, como de parte del Señor,
que son como aves del cielo que abandonaron sus moradas en el invierno,
y que la mano del Señor las derribará. Y que consideren los orgullosos y arrogantes,
que se atreven a decir que todas sus obras, ya sean buenas o malas, se hacen en Dios,
y que todo lo que realizan es obra Suya, aunque sea malo;
que éstos sepan que están en el espíritu diabólico y desenfrenado,
alegrándose muy por encima de la Vida pura e inocente.
Que los tales se humillen y sepan, sí, como de parte del Señor,
que su vida está destinada a la muerte y sus obras al juicio;
porque la Semilla santa se levantará y herirá la cabeza de la serpiente,
y la serpiente no podrá salvarla con toda su manipulación,
ni apartar sus obras engañosas del juicio de Dios;
sino que todo lo que ha edificado deberá ser desfigurado,
y todas sus obras deberán ser destruidas.
