[short="Capítulo VIII -- El Nuevo Nacimiento en la Regeneración"]
== Capítulo VIII. El Nuevo Nacimiento en la Regeneración, y las artimañas de la serpiente.

El hombre, habiéndose degenerado del santo orden de la creación pura,
y habiendo caído bajo el poder de la serpiente (que es un obrero sutil y fraudulento),
tiene ahora todas sus facultades y propiedades en un estado de desorden,
caos y confusión, y a menos que sea regenerado y nazca de nuevo,
no puede regresar al lugar donde estaba en la creación
pura donde disfrutaba de la presencia pura de Dios;
ni puede acercarse al Árbol de Vida,
sino que está excluido y es detenido por la espada encendida.
Porque lo inmundo no puede entrar en lo puro,
ni puede acercarse para comer de la santa Vida,
sino que debe ser cortado y consumido por la espada,
y el hombre debe pasar por el horno de fuego antes
de poder heredar el reino o poseer la vida eterna.
Por esta razón es dada la Luz, para descubrir todos los caminos del hombre,
a fin de que regrese y llegue a poseer nuevamente la Vida de la cual se
ha degenerado y caído. Con esta Luz es convencido en su propia conciencia
de las cosas que son malas para que no permanezca en ellas,
sino que las abandone, las niegue y siga a la Luz fuera de ellas.
Y a medida que el hombre obedece la Luz de Cristo,
así conoce eso que no sólo lo convence de pecado,
sino que también es suficiente para salvarlo y redimirlo del pecado,
destruyendo el cuerpo de pecado,
y restaurándolo al santo orden de la creación pura
donde una vez disfrutó de la presencia de Dios,
y era "`bueno`" ante Sus ojos.

Esta es la misma Luz que busca a todos los hombres perdidos,
y se manifiesta para salvarlos y redimirlos de su condición perdida.
Y todos los que han creído en ella a través de los siglos y de las generaciones,
han experimentado la obra eficaz de Su poder, por el que han sido redimidos de la tierra,
y de las vanas conductas del mundo,
y han caminado como peregrinos y extranjeros en el mundo.
Esta Luz pura estaba con Abel, y en ella él hizo el sacrificio,
y su sacrificio fue aceptado.
Estaba con Set, y en ella invocó el nombre del Señor.^
footnote:[Génesis 4:26]
Estaba con Noé,
y en ella fue preservado cuando el diluvio vino sobre
el mundo de los impíos. Estaba con Abraham,
y él creyó, y le fue contado por justicia.
Estaba con Isaac, y en ella se convirtió en heredero de la promesa.
Estaba con Jacob, y en ella venció el monte de Esaú. Estaba con Moisés,
y en ella guió a la heredad de Dios fuera de Egipto.
Estaba con David, y en ella su reino fue exaltado.
Estaba con Job, y en ella fue redimido,
sabiendo que su Redentor vivía. Estaba con Isaías,
y en ella vio al Niño que había nacido y al Hijo que había sido dado.
Estaba con Juan el Bautista,
y en ella vio al Cordero de Dios y contempló la gloria del unigénito del Padre.

Esta Luz pura de la Semilla santa de Cristo ha recorrido todas las generaciones,
y se ha manifestado a través de las distintas dispensaciones y
administraciones según le ha complacido al Padre de los espíritus.
Y en la medida que los hombres han creído en ella, no han permanecido en tinieblas,
ni han continuado satisfaciendo los deseos lujuriosos de la parte carnal,
sino que han sido regenerados por medio de la obra efectiva de Su poder,
mediante la cual quedaron muertos al pecado y vivos para Dios.
Mediante ella nacieron de la Semilla santa, la cual los hizo hombres santos,
y fueron llenados y divinamente inspirados por ella,
y testificaron a favor del Señor en Su poder.
La Luz manifestada en todos ellos era la misma,
y nunca ha cambiado su carácter o propiedad, aunque se manifiesta de varias maneras.
Y todos los hombres santos que publicaron las Escrituras,
tenían el nombre y la naturaleza de esta santa Semilla,
y nacieron de ella mediante la regeneración. En realidad,
esta obra fue forjada en los hombres antes de que se escribieran las Escrituras,
y fue la misma que obró en los que las escribieron,
y ha sido la misma en todas las generaciones desde que las Escrituras fueron escritas.
Esta es la obra de Cristo, la santa Semilla,
y solo a Él le pertenece regenerar y hacer nuevo al hombre,
porque ningún hombre puede añadir nada a la obra de regeneración,
ya que es una obra interna realizada por un poder invisible.

Y hay un remanente que testifica fielmente de esta obra hoy,
a quien el Señor ha escogido para ser Su pueblo adquirido.
Porque cuando un hombre se vuelve a la Luz de Cristo en su propia conciencia,
ésta le revela su condición, le manifiesta cada cosa secreta,
y le muestra todo lo que la serpiente ha engendrado
y a lo que la serpiente ha llevado su vida,
manifestándole claramente al entendimiento que esas cosas son malas y pecaminosas.
Y cuando un hombre se vuelve a la Luz y la obedece,
ella lo conduce fuera del mal que le ha manifestado,
y de esa forma el hombre es convencido y convertido.
Y aunque la serpiente hace guerra,
y trabaja para sujetar a los hombres en esas cosas que ella ha engendrado, sin embargo,
mientras el hombre una su voluntad a la Luz,
recibirá fuerzas para enfrentarla y también para vencerla.
Sin embargo, después de que un hombre es convencido,
convertido y vuelto a la Luz, se enfrenta a una gran lucha de aflicciones,
y debe atravesar muchos conflictos dolorosos antes
de poder someter a la serpiente bajo sus pies.
Y tras la conversión, la serpiente lo ataca aún más,
y se esfuerza por detenerlo en su camino,
de modo que a veces los hombres son detenidos por las obras sutiles de Satanás,
y son incapaces de avanzar y de despojarse de esas cosas
de las que desean apartarse en obediencia a la Luz.
La manera en que la serpiente realiza esto es arrastrando
al hombre al razonamiento y a la consulta,
para que considere lo que podría pasar si se aparta,
renuncia y se separa de esas cosas de las que está convencido que son malas.
Es en este lugar donde muchos han sentido la guerra del dragón contra el Cordero inocente,
que lucha para ser libre de las cosas corruptibles que han oprimido a la Vida inocente.
Y si el hombre obedece a la serpiente, y se sumerge en tales razonamientos,
el velo permanece sobre él, y no ve sino gran pérdida en apartarse de todo mal;
y bajo este velo muchos tropiezan con la Luz, retroceden y dejan de seguirla,
aunque por un tiempo la hayan obedecido en ciertas cosas.
Este es el hombre que ama algo más que a Cristo,
y que no puede desprenderse de su propia vida para ganar la vida eterna.

Así es como obra la serpiente antigua para defender su reino, y sin embargo,
muchos han derribado sus fortalezas y han sido liberados
de sus ataduras por el poder de la Luz,
que cuando se le presta atención y es obedecida,
aleja la mente de las cosas que son malas, se levanta en poder para juzgarlas,
y las crucifica sobre la cruz.
De este modo, el hombre muere al mal y el mal muere en el hombre.
Por ejemplo, cuando un borracho se vuelve a la Luz y la obedece,
lo primero que ella hace es convencerlo de que la embriaguez es un pecado,
luego lo saca de ella, destruye esa obra de tinieblas,
y aleja la vida del hombre de ella.
Esta es la obra de Jesucristo,
quien se manifiesta para destruir las obras del diablo
y para quemarlas con un fuego que nunca se apagará,
a fin de que el hombre pueda ser liberado de la carga de la corrupción.
Y todo lo que la serpiente ha producido en el hombre desde el principio,
y hacia lo que ha arrastrado el corazón del hombre
para que lo codicie y se deleite en eso,
es derribado con un golpe terrible de juicio cuando aparece la Luz.
Y mientras el hombre crea en la Luz, ésta continúa obrando,
apareciendo en poder para destruir cada deseo,
por medio del cual la serpiente domina al hombre y hace guerra contra su alma.
Y en la medida que el hombre se niegue a sí mismo, tome su cruz y siga fielmente la luz,
así "`muere cada día,`" (1 Corintios 15:31) y el poder hace
una separación entre lo precioso y lo vil,
y así llega a conocer a Aquel cuyo aventador está en su mano,
y cuyo fuego se hará sentir para quemar toda la paja.

Ahora, mientras un hombre permanezca fiel en este día,
y se mantenga en los justos juicios, el viejo hombre será crucificado,
y todas sus obras consumidas,
de manera que ni el pecado manifiesto ni la apariencia de piedad prevalecerán,
sino que todo lo altivo será derribado,
e incluso el más fuerte de los enemigos se doblegará. Porque este fuego no perdonará,
sino que pasará por todas las propiedades terrenales, y todo lo terrenal será quemado.
Y si el hombre tan solo permaneciera firme en este día, y se mantuviera en la paciencia,
entonces "`el juicio lo llevará a la victoria`" (Mateo 12:20),
y llegará a estar muerto a sí mismo y vivo en Cristo,
experimentando que la Luz no solo le muestra su pecado y lo convence de él,
sino que si se vuelve, obedece y cree, Ella elimina el pecado,
y limpia la conciencia de obras muertas,
y lo redime de toda codicia engendrada por la serpiente.
Así el hombre sabe con certeza que "`su Redentor vive,`" y que la salvación
se experimenta en la Luz que condena todo pecado en la carne.

De este modo, el borracho es redimido de la embriaguez, el que maldice de maldecir,
el mentiroso de la mentira, el hombre avaro de su avaricia, y el iracundo de su ira,
y todos son redimidos de sus vanos placeres, juegos, bromas, naturaleza salvaje,
testarudez, costumbres,
modas y tradiciones que existen en el mundo por causa de la concupiscencia.
Porque la Luz escudriña y descubre toda cosa secreta de la vieja naturaleza lujuriosa,
y la lleva a juicio, de modo que la serpiente no tiene escapatoria,
sino que el juicio cae sobre su cabeza.
Y aunque transcurra mucho tiempo antes de que el hombre pueda rendirse verdaderamente
a la negación de todas las cosas de las que está convencido que son malas,
o antes de que pueda atravesar claramente el desierto,
o ser testigo de una perfecta regeneración mediante el fuego de purificación;
a pesar de ello, en tanto que el hombre crea en la Luz y la siga,
la obra continúa y prospera, las obras codiciosas y malas van muriendo,
y la serpiente se va debilitando,
de manera que no se acerca al hombre con tanta furia y fuerza como antes.
De hecho, sus tentaciones son cada vez más débiles,
y el hombre va creciendo cada vez más fuerte en la Luz,
y se mantiene con valentía para resistirla.
Y a medida que el hombre experimenta el dominio sobre la serpiente,
y que es capaz (al permanecer en la Luz) de resistirla, aumentan su fuerza y su coraje,
y se mantiene valiente en el día de batalla, no se rinde cuando llegan las tentaciones,
sino que las somete y las pisotea.
Y luego,
cuando la serpiente aparece para tentar al hombre a caer
en los deseos contra los que se encuentra haciendo guerra,
él está preparado, y sale contra ella en su primera aparición,
poniendo el verdadero juicio sobre su cabeza, e hiriéndola en el poder de la Luz.

Porque el gran plan de la serpiente es: mantener al hombre vivo para sí mismo,
para que se deleite en los deseos de su propio corazón,
donde el enemigo mantiene dominio sobre él, y lo cautiva conforme a su voluntad.
Y por esta razón,
muchas tentaciones vienen sobre el hombre tras haber sido
convencido y haber llegado a reconocer la verdad de Dios.
Cuando se convierte y se vuelve al Señor, a menudo se ve muy acosado en su camino,
y con frecuencia casi obligado a retroceder.
De aquí se levanta la gran y fuerte guerra que enfrenta un hombre en su caminar espiritual,
dándose cuenta de la ardua labor para llegar a un estado de regeneración;
porque debe negarse a sí mismo, abandonar los deseos de su corazón, dar toda su vida,
y permanecer en el fuego del juicio.
Durante este viaje se pueden sentir las dos naturalezas contrarias luchando entre sí,
y se comprueba que la puerta es angosta, y que son pocos los que la encuentran.
Pero a medida que un hombre se mantiene fiel y permanece en la Luz,
crece en fuerza y aprende a resistir cuando el enemigo lo persigue con vehemencia,
y finalmente se erigirá vencedor sobre todos los
deseos que una vez tuvieron dominio sobre él.

Sin embargo,
cuando la serpiente descubre que no puede retener al hombre en sus afectos desmesurados,
ni llevarlo a satisfacer plenamente sus deseos como solía hacerlo,
entonces sutilmente disminuye la tentación,
y persuade al hombre de que puede hacer uso de las cosas con moderación,
y sólo evitar el exceso;
diciéndole que el exceso es lo único que hace que algo sea malo y condenable.
De modo que le dice al borracho que puede beber con moderación,
hacerle compañía a sus amigos y divertirse con ellos.
Y le dice al altivo de corazón,
que puede vestirse elegantemente según su posición en la sociedad,
si tan solo se mantiene lejos del exceso.
De esta manera pone la serpiente muchas otras tentaciones,
insistiendo que el uso moderado de las cosas no traerá condenación. Pero en este punto,
muchos han descubierto que es una mentirosa;
porque cuando dejaron el exceso y comenzaron a vivir en lo que el diablo llama moderación,
allí se encontraron todavía alimentando los deseos de su corazón,
y sintiéndose condenados y juzgados en su corazón por la Luz.
Y éstos no pudieron hallar descanso ni paz hasta que el diablo fue totalmente negado,
y el deseo del corazón rendido a la cruz para ser crucificado;
y así la redención se lleva a cabo de manera perfecta
en el corazón mediante el poder de Cristo.
Y solamente así es como ellos encuentran el uso correcto de todas las cosas,
y su lugar apropiado en la verdadera moderación. Porque los que
son verdaderamente redimidos pueden utilizar la creación sin condenación,
recibiendo y usando todas las cosas en el temor del Señor,
de acuerdo con lo que es útil y no más;
porque el deseo de la carne ya no reina en el corazón,
ni se extiende más allá de la necesidad presente.

Y ahora, compartiré una experiencia verdadera y fiel,
aunque se podrían mencionar muchas otras:
Sé de un hombre que una vez vivió para sí mismo,
complaciendo todos sus deseos y amando sus placeres más que a Dios.
Y había una cosa en particular en la que la serpiente
le había enseñado a encontrar su vida,
y él se deleitaba principalmente en ella.
Después de que llegó a obedecer la Luz de Cristo en su conciencia,
se le mostró claramente que eso era sobremanera malo.
Y a pesar de que seguía a la Luz y se mantenía bajo
la cruz con respecto a este deseo lujurioso,
el diablo no dejaba de provocarlo fuertemente para que complaciera el deseo.
Por un tiempo el terror del Señor estuvo sobre él, y Su justo juicio lo alcanzó,
y fue muy azotado por el mal.
Pero entonces la serpiente le dijo: "`Solamente debes disminuir tu afecto desmedido,
y entonces no te sucederá más.`" Entonces el hombre dejó de usar mucho esta cosa,
y comenzó a utilizarla menos, hasta que casi la dejó de usar del todo.
Pero, aun así, el juicio del Señor continuó persiguiéndolo,
y el terror se incrementó sobre él,
y fue justo que el Santo Dios lo tratara así. Este hombre no pudo
encontrar paz hasta que renunció a su vida en cuanto al deseo,
y aprendió a mantenerse en guardia,
de modo que cada vez que la serpiente se acercaba con esa tentación,
el juicio era puesto sobre su cabeza.
Así aprendió a caminar en la cruz diaria, hasta que él fue crucificado al deseo,
y el deseo fue crucificado a él,
y ahora permanece tan muerto como si nunca hubiera existido.
¡Gloria al Señor por siempre, que se encargó del caso y perfeccionó Su propia obra!

Sin embargo,
el hombre que no llega a experimentar el deseo crucificado desde su raíz y fundamento,
es engañado en una falsa moderación, y al mantenerse allí,
se ve a sí mismo por encima de muchos otros que aún permanecen en el afecto desmesurado.
De esta manera obra la serpiente ingeniosamente,
para mantener al hombre lejos del horno y apartarlo del juicio;
y aunque es posible que el afecto desmesurado disminuya, aun así,
el deseo no es crucificado y la vida del deseo se preserva.
De ese modo, el hombre huye por su vida,
y en lugar de negarse a sí mismo y tomar la cruz, niega la cruz para salvarse a sí mismo,
huyendo del juicio y buscando esconderse de la luz del Día.

Sin embargo, a medida que el hombre se mantiene en la Luz,
el camino se hace más fácil,
y es capacitado para atravesarlo y para llegar al final de él,
y vencer a la serpiente que obra en su contra.
Y conforme sigue fielmente a la Luz, ésta no sólo lo lleva al juicio,
sino que lo mantiene en el juicio,
y allí aprende a esperar "`hasta que el juicio sea llevado a la victoria.`"^
footnote:[Mateo 12:20--Traducción literal de la KJV.]
Y mientras permanezca dispuesto y se mantenga bajo la cruz diaria,
rindiendo con gozo todos los deseos de su corazón para que sean crucificados,
llegará a sentir muerta la enemistad que ha sido engendrada y alimentada por el deseo.
Porque cuando el hombre pasa por el horno y permanece en el fuego purificador
en el que se hace una separación y lo corruptible se quema y se destruye,
la Semilla santa se muestra sin mezcla alguna,
y la creación es liberada de la aflicción y del dolor.
En este horno de fuego el hombre es regenerado, el viejo hombre es destruido,
los deseos de su corazón son crucificados, el cuerpo del pecado es consumido,
y la escoria y el estaño son separados del oro.
Solo mediante esta operación u obra viva, el hombre es rescatado de la caída,
y la creación pura es restaurada a su orden santo,
y el hombre es redimido de las propiedades caídas donde codicia el mal;
así regresa al paraíso de Dios y al Árbol de la Vida,
y encuentra que la espada encendida ya no lo mantiene separado.

Esta es la regeneración que el hombre debe experimentar en el fuego refinador,
donde tiene que desprenderse de todo lo suyo (tanto de su inmundicia como
de su justicia) y atravesarlo sin aferrarse a ninguna cosa impura,
o de lo contrario, no podrá entrar al reino de Dios.
Porque el hombre tiene que despojarse de la parte
corruptible en la que permanece en la degeneración,
antes de que pueda ser restaurado al santo orden de la creación pura.
Y en la medida en que se despoja del viejo hombre en el fuego purificador,
y permanece en la obra de regeneración, llega a lo nuevo, y lo nuevo nace en él,
y se produce un cambio por el cual es redimido de las propiedades
caídas e introducido al santo orden de la Vida.
Entonces deja de pertenecerse a sí mismo, ni puede satisfacer más sus deseos,
sino que se encuentra verdaderamente muerto a ellos,
y su vida se renueva en el nacimiento de la Semilla santa, de la que ha nacido.
Así se despoja de la borrachera y muere a ese deseo,
se reviste de sobriedad y vive en la virtud de Cristo.
O se despoja de la ira y muere a ese deseo,
se reviste de mansedumbre y vive en la virtud de Cristo.
O se despoja de la envidia y muere a ese deseo,
se reviste de amor y vive en la virtud de Cristo.
Y así,
todo lo que la serpiente ha engendrado a través de su obra
engañosa y que permanece en la vieja naturaleza codiciosa,
es juzgado por la Luz, crucificado por el poder y consumido en el fuego,
de manera que el hombre es limpiado de toda contaminación,
y el camino queda libre para que el santo Nacimiento brote,
y para que reine el Cordero que fue inmolado.
Y así,
se puede verdaderamente decir que "`morir es ganancia,`" y "`bienaventurados
los muertos que mueren en el Señor,`" porque llegan a heredar la vida e inmortalidad,
a poseer las riquezas duraderas y la vida eterna,
al ser herederos de Dios y coherederos con Cristo, en quien son hechos un hombre nuevo,
llevando una imagen celestial en la que es glorificado el Padre.
