== Capítulo IX. La Nueva Creación en el Santo Orden

El Señor Dios de la gloria eterna busca al hombre en su estado caído y degenerado,
y con Su Luz pura lo encuentra lejos,
con sus pies caminando por caminos de oscuridad en la tierra de desolación,
y allí lo visita en su condición pobre y miserable.
Porque el hombre ha caído de Dios y se ha separado de su Hacedor.
La serpiente lo ha engañado,
y con su astucia lo ha arrastrado lejos del santo orden y ha seducido
su mente hacia las propiedades caídas de la parte visible de la creación,
donde se convierte en un siervo del sutil engañador,
satisfaciendo los deseos de su propio corazón carnal, y pecando contra el Dios santo.
Y en este caos de los afectos desordenados, la creación pura permanece bajo servidumbre,
sufriendo muchos dolores,
y los viejos cielos y la vieja tierra están sobre ella oprimiéndola fuertemente.
Y en este estado caído, el hombre nunca encuentra reposo,
ni su corazón se sacia de su codicia,
sino que vive separado del Dios de misericordia y
sumergido en la profundidad de la miseria.
¡Ay!
Es un pecador, y la muerte reina sobre él, y la ira está sobre él,
y en el caos de sus afectos desordenados,
su vida es llevada y sacudida de un lado a otro, y no hay estabilidad en él.

Pero en este estado perturbado se levanta un clamor al Señor,
y se exhalan suspiros en busca de un verdadero descanso, y el Señor los escucha,
y en gran misericordia se levanta para ayudar, extiende Su brazo y derriba muchos montes.
Llega con Su poder y hace que los collados se derritan.
Él emite Su voz y la tierra tiembla,
enciende un fuego que consume la parte terrenal hasta las cenizas.
De ese modo lleva al hombre a la nadedad, y disuelve el primer nacimiento hasta el polvo,
y hace que los viejos cielos pasen con clamor,
fundiendo los elementos con fuego abrasador.
Y así, el hombre ya no encuentra su vida en tales cosas,
sino que esa vida le es arrebatada, y él es asesinado y muerto,
hasta que el Espíritu de Vida de Dios llega sobre él para
crearlo de nuevo en el santo orden de la vida,
dándole aliento y un ser como el que tenía en el principio.

Porque es hecho y formado nuevamente por la mano de Dios, y es hechura Suya,
en quien ahora recibe su vida, y de cuyo Espíritu obtiene su aliento,
y así es perfectamente renovado en el espíritu de su mente,
no teniendo nada de lo viejo sobre sí, ni partes terrenales morando en él. Sí,
mediante el fuego purificador es limpiado, brota del vientre de la virgen,
y bebe de los pechos que dan la verdadera vida, por lo que crece en fuerza,
incrementa su sabiduría,
y llega a la estatura de la plenitud de Cristo como participante de la naturaleza divina.
De esta manera, todas las cosas viejas son quitadas y desechadas en el fuego purificador,
y sale del horno como un niño desnudo, como una nueva creación,
para levantarse juntamente con el Cordero en Su naturaleza,
para ser revestido con la gloria de la preciosa Perla,
y restaurado en el santo orden de la Vida.
Su alimento proviene del Árbol de la Vida,
y su camino se sustenta en el poder y sabiduría de la Semilla que ha llegado a dominar,
y que ahora reina en pureza sin mezcla alguna.

Pero sólo conforme el hombre permanece en el fuego y espera en el juicio,
es despojado de las cosas viejas en las que ha vivido, y es revestido de lo nuevo,
siendo trasladado del reino de la oscuridad al reino de Su amado Hijo.
Porque en la medida que el hombre cree en la Luz que se
manifiesta en su conciencia (que resplandece de la Vida),
así se acerca a la justicia de Dios, que dicta sentencia contra él,
lo condena a muerte y lo crucifica en la cruz.
De este modo, el hombre muere verdaderamente a sí mismo,
junto con todos los deseos de su corazón en pensamiento, palabra y obra,
y recibe a Cristo, la Semilla de una nueva vida, aprende a revestirse de Él,
y experimenta que Cristo le ha sido hecho sabiduría, justicia,
santificación y redención. Así atraviesa los seis días de trabajo,
donde toda la escoria se consume en el horno,
y llega al séptimo día donde descansa con Dios de todas sus obras,
y se sienta en el poder y sabiduría de la Semilla santa,
reposando en la quietud de la naturaleza divina y
en el orden santo de la nueva creación. De este modo,
la nueva creación es terminada junto con todas sus huestes,
tras haber sido sometida al santo orden mediante la obra eficaz del santo poder.
Así el hombre es verdaderamente cambiado y renovado
por el santo nacimiento de la Semilla inmortal,
y colocado nuevamente en el paraíso de Dios,
no siendo más mantenido fuera por la espada encendida,
sino teniendo acceso diario al Árbol de la Vida Eterna.
