[short="Capítulo X -- Las Obras del Hombre en la Nueva Creación"]
== Capítulo X. El Camino y las Obras del Hombre en la Nueva Creación

Por medio de esta restauración el hombre es transformado,
se convierte en un nuevo hombre en Cristo, y su camino y todas sus obras son nuevas.
Se vuelve un hacedor de bien, y es aceptado por Dios en Cristo el Amado.
Aquí encuentra el Camino nuevo y vivo que lo hace un hombre nuevo y vivo,
y lo guía al Dios vivo.
Este es el Camino de Santidad por el que andan los pies limpios,
y el hombre que anda en este camino, se encuentra en el camino de paz,
y es guiado a los delicados pastos de refrigerio eterno,
y anda continuamente junto a arroyos placenteros,
y su viaje es a lo largo de ese río que alegra a toda la ciudad de Dios.
Su vida está ligada a la Vida santa de la Semilla
inmortal y se mueve con ella dondequiera que vaya,
y no avanzará sino por Su orden y por Su fuerza.
Y a medida que el hombre se mantiene en estrecha comunión con la Semilla,
es fortalecido para recorrer el camino de todo mandamiento
y no hay debilidad en sus lomos,
sino una fuerza perfecta que permanece en el movimiento de la Semilla santa,
que lo lleva sobre alas de águila, corriendo sin cansarse, y caminando sin fatigarse.
Su camino se vuelve santo,
sus obras son "`santas a Jehová,`" y es hecho nuevo en Jesucristo para caminar en ellas.
Sí, tal hombre ya no se pertenece, sino que está a la disposición del Señor,
sirviendo sinceramente a su Dios en justicia y en verdadera santidad.
Deja de pensar sus propios pensamientos, no habla sus propias palabras,
ni realiza sus propias obras,
sino que es movido y actuado en el poder y la sabiduría de la Semilla santa,
de la que ha nacido y ha sido hecho una nueva criatura.

De ese modo es cambiado el hombre y es hecho un hombre santo, un hombre justo,
un hombre piadoso, sobrio, puro, humilde, paciente, amoroso, amable, bueno, sencillo,
suave de corazón, tolerante, sufrido,
y en todas las cosas camina según el orden de la Vida santa, en la que ha nacido,
vive y se mueve.
En realidad, se convierte en un cordero en la naturaleza del Cordero,
y es hermoso en el resplandor y santidad de la gloria de la Perla.
Y así es trasladado y cambiado el hombre, mediante la obra eficaz del gran poder de Dios.
Glorifica a su Hacedor con un corazón nuevo,
y es sincero y recto en su corazón delante de Dios.
El Señor Dios se complace en él, y aprueba su camino y su obra, y lo justifica en ello.
Entonces no hay más condenación sobre él, ni ninguna ira o maldición que salga contra él,
o caiga sobre él, sino que habita en el amor eterno, y el amor habita en él,
y lleva su imagen, limpia de toda contaminación, mancha, o defecto.
De modo que la gloria resplandece desde la Perla preciosa,
y el cetro del Cordero ejerce su dominio, y Él es exaltado sobre Su trono.
Él reviste a Sus santos con justicia pura, y coloca coronas de oro puro sobre sus cabezas.
Y así descansan con Él en la tierra santa y se mueven en el santo orden de la vida,
cantando las canciones de santidad y alabanza dentro de las puertas
de la nueva Jerusalén. Porque el Cordero los llena de gozo y alegría,
y les da un corazón nuevo y un espíritu nuevo que proclaman Su nombre,
y nunca dejan de darle gloria, honor, acción de gracias,
alabanza y aleluyas Al que se sienta sobre el trono.
